/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bankChooser.java
 *
 * Created on 23/Abr/2011, 20:41:04
 */
package bankStartup;

import DAO.BankDAO;
import DAO.MysqlDAO.MysqlBankDAO;
import DAO.MySQLExceptions.EmptySetException;
import DAO.MySQLExceptions.UnknownRegistException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListDataListener;
import Principal.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author jhorgemiguel
 */
public class bankChooser extends javax.swing.JFrame {

    BankDAO bank;
    
    /** Creates new form bankChooser */
    public bankChooser() throws SQLException, ClassNotFoundException{
        initComponents();
        updateBankList();
    }

    public void updateBankList() throws SQLException, ClassNotFoundException {

        List<Beans.Bank> banks = null;
        try {
            bank = new MysqlBankDAO();
            banks = bank.findAllBanks();
        } catch (EmptySetException ex) {
            Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultListModel nameBank = new DefaultListModel();       
        for (Beans.Bank b : banks){
            nameBank.addElement(b.getBankName());
        }       
        banksList.setModel(nameBank);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        banksList = new javax.swing.JList();
        bankSelect_btn = new javax.swing.JButton();
        createBank_btn = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Principal.PrincipalMenuApp.class).getContext().getResourceMap(bankChooser.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        banksList.setName("banksList"); // NOI18N
        banksList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banksListMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(banksList);

        bankSelect_btn.setText(resourceMap.getString("bankSelect_btn.text")); // NOI18N
        bankSelect_btn.setName("bankSelect_btn"); // NOI18N
        bankSelect_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankSelect_btnActionPerformed(evt);
            }
        });

        createBank_btn.setText(resourceMap.getString("createBank_btn.text")); // NOI18N
        createBank_btn.setName("createBank_btn"); // NOI18N
        createBank_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBank_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(createBank_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bankSelect_btn))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankSelect_btn)
                    .addComponent(createBank_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankSelect_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankSelect_btnActionPerformed
        
        PrincipalMenuApp menu = PrincipalMenuApp.getApplication(); 
        try {            
            try {
                MysqlBankDAO bankIn;
                bankIn = new MysqlBankDAO();
                menu.menuStartup(bankIn.findBankByName(banksList.getSelectedValue().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
            } catch (EmptySetException ex) {
                Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownRegistException ex) {
            Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_bankSelect_btnActionPerformed

    private void createBank_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBank_btnActionPerformed
        // TODO add your handling code here:
        JFrame newBank = new bankCreator();
        newBank.setVisible(true);
    }//GEN-LAST:event_createBank_btnActionPerformed

    private void banksListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banksListMouseEntered
        try {
            // TODO add your handling code here:
            updateBankList();
        } catch (SQLException ex) {
            Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_banksListMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new bankChooser().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(bankChooser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bankSelect_btn;
    private javax.swing.JList banksList;
    private javax.swing.JButton createBank_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
