/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bankCreator.java
 *
 * Created on 23/Abr/2011, 20:51:27
 */
package bankStartup;

import Beans.*;
import DAO.MysqlDAO.MysqlBankDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jhorgemiguel
 */
public class bankCreator extends javax.swing.JFrame {

    /** Creates new form bankCreator */
    public bankCreator() {
        initComponents();
    } 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bankName_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bankRefDate_txt = new javax.swing.JTextField();
        bankCreate_btn = new javax.swing.JButton();
        cancelBankCreation_btn = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Principal.PrincipalMenuApp.class).getContext().getResourceMap(bankCreator.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        bankName_txt.setText(resourceMap.getString("bankName_txt.text")); // NOI18N
        bankName_txt.setName("bankName_txt"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        bankRefDate_txt.setText(resourceMap.getString("bankRefDate_txt.text")); // NOI18N
        bankRefDate_txt.setName("bankRefDate_txt"); // NOI18N
        bankRefDate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankRefDate_txtActionPerformed(evt);
            }
        });

        bankCreate_btn.setText(resourceMap.getString("bankCreate_btn.text")); // NOI18N
        bankCreate_btn.setName("bankCreate_btn"); // NOI18N
        bankCreate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankCreate_btnActionPerformed(evt);
            }
        });

        cancelBankCreation_btn.setText(resourceMap.getString("cancelBankCreation_btn.text")); // NOI18N
        cancelBankCreation_btn.setName("cancelBankCreation_btn"); // NOI18N
        cancelBankCreation_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBankCreation_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelBankCreation_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankCreate_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bankRefDate_txt)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bankName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bankRefDate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankCreate_btn)
                    .addComponent(cancelBankCreation_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankRefDate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankRefDate_txtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bankRefDate_txtActionPerformed

    private void cancelBankCreation_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBankCreation_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelBankCreation_btnActionPerformed

    private void bankCreate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankCreate_btnActionPerformed
        // TODO add your handling code here:
        Bank newBank = new Bank(bankName_txt.getText(), dateConverter(bankRefDate_txt.getText()));
        try {
            MysqlBankDAO myBankDAO;
            myBankDAO = new MysqlBankDAO();
            myBankDAO.insertBank(newBank);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
                Logger.getLogger(bankCreator.class.getName()).log(Level.SEVERE, null, ex);           
        } catch (SQLException ex) {
            Logger.getLogger(bankCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bankCreate_btnActionPerformed

    //Convert String to Date Type
    public Date dateConverter(String data){
        SimpleDateFormat deta = new SimpleDateFormat("yyyy/MM/DD");
        String birthDate = data;
        Date newDate = new Date();
        try {
            newDate = deta.parse(birthDate);
        } catch (ParseException ex) {
            Logger.getLogger(bankCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
        return newDate;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new bankCreator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bankCreate_btn;
    private javax.swing.JTextField bankName_txt;
    private javax.swing.JTextField bankRefDate_txt;
    private javax.swing.JButton cancelBankCreation_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
