/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListClients.java
 *
 * Created on 23/Abr/2011, 16:26:42
 */
package clients;

import Beans.Client;
import DAO.MySQLExceptions.EmptySetException;
import DAO.MysqlDAO.MysqlClientDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author jhorgemiguel
 */
public class ListClients extends javax.swing.JFrame {

    MysqlClientDAO clientDAO = null;
    private int bankID;
    
    /** Creates new form ListClients */
    public ListClients() {
        initComponents();
    }

    public ListClients(int bankID){
        this();
        this.bankID = bankID;
        updateClientList(bankID);
    }
    
    public void updateClientList(int BankID){
        List<Client> clients = null;
        try {
            clientDAO = new MysqlClientDAO();
            clients = clientDAO.findAllClients(bankID);
        } catch (EmptySetException ex) {
                Logger.getLogger(ListClients.class.getName()).log(Level.SEVERE, null, ex);    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListClients.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ListClients.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultListModel clientsModel = new DefaultListModel();
        for (Client c : clients){
            String s = c.getName() + " - NIF: " + c.getClientNIF();
            clientsModel.addElement(s);
        }
        clientsList_lst.setModel(clientsModel);
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientsList_lst = new javax.swing.JList();
        showClientList_btn = new javax.swing.JButton();
        closeClientList_btn = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Principal.PrincipalMenuApp.class).getContext().getResourceMap(ListClients.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        clientsList_lst.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cliente 1 - NIF - Contas associadas", "Cliente 2 - NIF - Contas associadas", "Cliente 3 - NIF - Contas associadas" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        clientsList_lst.setName("clientsList_lst"); // NOI18N
        jScrollPane1.setViewportView(clientsList_lst);

        showClientList_btn.setText(resourceMap.getString("showClientList_btn.text")); // NOI18N
        showClientList_btn.setName("showClientList_btn"); // NOI18N
        showClientList_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showClientList_btnActionPerformed(evt);
            }
        });

        closeClientList_btn.setText(resourceMap.getString("closeClientList_btn.text")); // NOI18N
        closeClientList_btn.setName("closeClientList_btn"); // NOI18N
        closeClientList_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeClientList_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(showClientList_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeClientList_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showClientList_btn)
                    .addComponent(closeClientList_btn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeClientList_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeClientList_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeClientList_btnActionPerformed

    private void showClientList_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showClientList_btnActionPerformed
        // TODO add your handling code here:
        updateClientList(bankID);
    }//GEN-LAST:event_showClientList_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListClients().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList clientsList_lst;
    private javax.swing.JButton closeClientList_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showClientList_btn;
    // End of variables declaration//GEN-END:variables
}
